name: Metrics
on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SourabhX16
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year
          plugin_lines: true
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SourabhX16
          base: ""
          config_timezone: Europe/Moscow
          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_trim: false
